### ISSUE TITLE
Not able to use a S3 repository with base_path

### ISSUE THREAD

**Issue by pmarjou22** [aiven/encrypted-repository-opensearch#21]
Hello,

Thanks for the plugin !

We are already using successfuly S3 plugin for S3 snapshots (following this documentation https://opensearch.org/docs/2.0/opensearch/snapshot-restore/#amazon-s3 with and access and secret keys) and would like to use your plugin to include client side encryption . We have successfully created private/public RSA keys, installed your plugin (in addition to S3 plugin already in place) and pushed keys to opensearch keystore following your documentation .

Using the same bucket that we use with for current S3 snaphot, we create a new repository have an error with base path

It seems the base path is duplicated somewhere

![image](https://user-images.githubusercontent.com/76211197/169716046-df48b150-a24d-4963-9955-0c8aea22bf9c.png)

We don't know where to use this setting 
encrypted.security_provider - fully qualified class name for the third party security provider, e.g. com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider

**Comment by willyborankin** [comment]
Hi @pmarjou22, thank you for reporting the issue. I fixed the problem, so today evening/tomorrow morning will prepare a new release. Regarding:
`encrypted.security_provider` - this property needs to be set in `opensearch.yml` configuration aka static configuration. By default the plugin uses Bouncy Castle security provider, which is not as performant as it could be. So If you want to replace it you need to add an additional security plugin jar file manually in the plugin installation directory. The reason why I did not add e.g. Amazon Corretto security provider is the lack of support for MS Window, Arm64 etc. Be careful this feature is experimental and I haven't finished all testing yet.

**Comment by willyborankin** [comment]
So the issue was fixed the new version is: `1.3.2.1`

**Comment by pmarjou22** [comment]
Hello, thanks a lot it works now !
